#!/usr/bin/env bash
set -eu

if [[ $# != 1 ]]; then
    echo "Usage: ./configure-proxy <name>"
    exit 1
fi

INSTANCE=$1

case $INSTANCE in
    epimodels)
        INSTANCE_HOST=epimodels.dide.ic.ac.uk
        ;;
    wodin-dev)
        INSTANCE_HOST=wodin-dev.dide.ic.ac.uk
        ;;
    localhost)
        INSTANCE_HOST=localhost
        ;;
    *)
        echo "Unknown instance name $INSTANCE"
        exit 1
        ;;
esac

echo $INSTANCE_HOST > hostname

if [[ $INSTANCE == "localhost" ]]; then
    echo "Configured http proxy (no ssl) for $INSTANCE_HOST"
else
    export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
    VAULT_TOKEN=$(vault login -method=github -token-only)
    export VAULT_TOKEN

    username=$(vault read -field=username "secret/certbot-hdb/credentials")
    password=$(vault read -field=password "secret/certbot-hdb/credentials")
    cat > hdb-credentials <<EOF
HDB_ACME_USERNAME=$username
HDB_ACME_PASSWORD=$password
EOF
fi
