#!/usr/bin/env bash
set -eu

# Can do this with SITES=(config/*) but it would pick up any file
# there too. This is the main thing to configure when adding a new
# site (or removing one)
SITES=(demo msc-idm-2022 malawi-idm-2022 gambia-idm-2023)

declare -A SITES_URL
declare -A SITES_REF

SITES_URL[demo]="https://github.com/mrc-ide/wodin-demo-config"
SITES_URL[msc-idm-2022]="https://github.com/mrc-ide/wodin-msc-idm-2022"
SITES_URL[malawi-idm-2022]="https://github.com/mrc-ide/wodin-malawi-idm-2022"
SITES_URL[gambia-idm-2023]="https://github.com/mrc-ide/wodin-gambia-idm-2023"

# Configure branches here
NETWORK=epimodels
APP_BRANCH=main
API_BRANCH=main
PROXY_BRANCH=main

# Nothing to change below here!
REDIS="--redis-url=redis://wodin-redis:6379"

if [[ ! -f hostname ]]; then
    echo "Did not find file 'hostname' in current directory"
    exit 1
fi

WODIN_HOST=$(cat hostname)
if [[ $WODIN_HOST == "localhost" ]]; then
    SSL=
    SSL_PORTS=
    PROTOCOL="http"
else
    SSL="--ssl"
    SSL_PORTS="-p 443:443"
    PROTOCOL="https"
fi

echo "*** Pulling images"
docker pull mrcide/odin.api:$API_BRANCH
docker pull mrcide/wodin:$APP_BRANCH
docker pull mrcide/wodin-proxy:$PROXY_BRANCH

docker network create $NETWORK 2> /dev/null || /bin/true
docker volume create redis-docker
docker volume create wodin-config

echo "*** Updating config"
SITES_ARGS=()
for SITE in "${SITES[@]}"; do
    SITES_ARGS+=(/config/$SITE ${SITES_URL[$SITE]} "${SITES_REF[$SITE]:-main}")
done
docker run --rm -v wodin-config:/config --entrypoint update-sites \
       mrcide/wodin:$APP_BRANCH ${SITES_ARGS[@]}

echo "*** Bringing down any old containers"
docker rm --force $(docker ps -qa -f 'name=wodin-') 2> /dev/null || /bin/true

echo "*** Starting wodin"

# Shared:
docker run -d --name wodin-redis -v redis-data:/data --network=$NETWORK redis:6
docker run -d --name wodin-api --network=$NETWORK mrcide/odin.api:$API_BRANCH

PROXY_SITE_ARG=""
for SITE in "${SITES[@]}"; do
    echo "Bringing up $SITE"
    docker run -d --name "wodin-$SITE" --network=$NETWORK \
           -v wodin-config:/wodin/config:ro \
           mrcide/wodin:$APP_BRANCH \
           --redis-url=redis://wodin-redis:6379 \
           --odin-api=http://wodin-api:8001 \
           --base-url=$PROTOCOL://$WODIN_HOST/$SITE /wodin/config/$SITE
    PROXY_SITE_ARG+="--site $SITE=wodin-$SITE:3000 "
done

docker run  -d --network $NETWORK --name wodin-proxy \
       -p 80:80 $SSL_PORTS \
       -v $PWD/root:/wodin/root:ro \
       mrcide/wodin-proxy:$PROXY_BRANCH \
       $WODIN_HOST $SSL $PROXY_SITE_ARG

if [[ $WODIN_HOST == "localhost" ]]; then
    echo "*** Not copying certificates, using http only"
else
    echo "*** Copying certificates"
    docker cp ssl/certificate.pem wodin-proxy:/run/proxy/
    docker cp ssl/key.pem wodin-proxy:/run/proxy/
fi

echo "*** Done, wodin should now be available at $PROTOCOL://$WODIN_HOST"
