#!/usr/bin/env bash
set -ex

HERE=$(dirname $0)
. $HERE/common

docker build --pull \
       --tag $TAG_SHA \
       --tag $TAG_BRANCH \
       $HERE

# We always push the SHA tagged versions, for debugging if the tests
# after this step fail
# docker push $TAG_SHA

if [ $GIT_BRANCH == "main" ]; then
   docker tag $TAG_SHA $TAG_LATEST
   # docker push $TAG_LATEST
fi
